name: stance_gator_dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - nvidia/label/cuda-11.8.0::cuda-toolkit

  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - --config-settings editable-mode=strict
    - -e ./
    - build

    # For convenience
    - huggingface_hub[cli]
    - ipykernel
    - ipywidgets