name: gatbert
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - ipykernel
  - pandas
  - pytorch
  - torchmetrics
  - transformers
  - lightning
  - python-graphviz
  - pip:
    - pykeen[transformers]
    - jsonargparse[signatures]
