name: gatbert
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - ipykernel
  - pandas
  - pytorch
  - torchmetrics
  - transformers
  - lightning
  - accelerate>=0.26.0

  - spacy
  - spacy-model-en_core_web_sm
  - gensim

  - plotly
  - nbformat>=4.2.0

  - pip:
    - pykeen[transformers]
    - jsonargparse[signatures]
