name: stance_gator_dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - nvidia/label/cuda-11.8.0::cuda-toolkit

  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - --config-settings editable-mode=strict

    - -f https://data.pyg.org/whl/torch-2.6.0+cu118.html
    # - -f https://download.pytorch.org/whl/torch_stable.html
    - torch==2.6.0+cu118

    - -e ./
    - build

    # For convenience
    - huggingface_hub[cli]
    - ipykernel
    - ipywidgets
