name: stance_gator_dev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - nvidia/label/cuda-11.8.0::cuda-toolkit

  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch
    - torchmetrics
    - transformers
    - lightning
    - accelerate>=0.26.0
    - jsonargparse[signatures]

    #- pandas
    #- plotly
    #- nbformat>=4.2.0
