name: stance_gator_dev
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - pip
  - nvidia/label/cuda-11.8.0::cuda-toolkit

  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - -e ./
    - build
